Repository wecode-bootcamp-korea/10-React-Westagram-4, pull requests merged in 2020-07, with the labels that each got.

#3 [배정규] refactor: arrow function 사용하여 함수 선언 및 reset.scss 적용
  src/Pages/junggyoo/Login/JunggyooLogin.js
  src/Pages/junggyoo/Login/Login.css
  src/Pages/junggyoo/Login/junggyooLogin.scss
  src/Pages/junggyoo/Main/Feeds/Feeds.css
  src/Pages/junggyoo/Main/Feeds/Feeds.js
  src/Pages/junggyoo/Main/Feeds/Feeds.scss
  src/Pages/junggyoo/Main/JunggyooMain.js
  src/Pages/junggyoo/Main/Main.css
  src/Pages/junggyoo/Main/Main.js
  src/Pages/junggyoo/Main/Nav/Nav.css
  src/Pages/junggyoo/Main/Nav/Nav.js
  src/Pages/junggyoo/Main/Nav/Nav.scss
  src/Pages/junggyoo/Main/Right/Right.css
  src/Pages/junggyoo/Main/Right/Right.js
  src/Pages/junggyoo/Main/Right/Right.scss
  src/Pages/junggyoo/Main/junggyooMain.scss
  src/Routes.js
  src/Styles/reset.scss
  src/index.js
Labels: 리뷰 요청

#4 [최운정] 충돌 해결
  public/images/weunjeong/close-button.png
  public/images/weunjeong/liz.jpg
  public/images/weunjeong/logo_text.png
  src/Pages/weunjeong/Login/Login.js
  src/Pages/weunjeong/Login/Login.scss
  src/Pages/weunjeong/Main/Components/Feeds/Emoji.js
  src/Pages/weunjeong/Main/Components/Feeds/Feeds.js
  src/Pages/weunjeong/Main/Components/Feeds/Feeds.scss
  src/Pages/weunjeong/Main/Components/Nav/ Nav.js
  src/Pages/weunjeong/Main/Components/Nav/Nav.scss
  src/Pages/weunjeong/Main/Components/Right/Right.js
  src/Pages/weunjeong/Main/Components/Right/Right.scss
  src/Pages/weunjeong/Main/Main.js
  src/Pages/weunjeong/Main/Main.scss
  src/Pages/weunjeong/test.js
  src/Routes.js
Labels: Status: Accepted

#5 [임현지] Refactor: Feeds & Right 컴포넌트 분리 및 scss파일 정리
  src/Pages/hyeonji/Login/Login.js
  src/Pages/hyeonji/Main/Feed/Feed.js
  src/Pages/hyeonji/Main/Feed/Feed.scss
  src/Pages/hyeonji/Main/Feeds/Feeds.js
  src/Pages/hyeonji/Main/Feeds/Feeds.scss
  src/Pages/hyeonji/Main/Main.js
  src/Pages/hyeonji/Main/Main.scss
  src/Pages/hyeonji/Main/Nav/Nav.js
  src/Pages/hyeonji/Main/Nav/Nav.scss
  src/Pages/hyeonji/Main/Right/Right.js
  src/Pages/hyeonji/Main/Right/Right.scss
Labels: Status: Accepted

#6 [이병훈] add : mainRight 추가 및 scss nesting 완료
  public/images/byeonghoon/IMG_7916.jpeg
  public/images/byeonghoon/logo_text.png
  src/Pages/byeonghoon/Login/Login.js
  src/Pages/byeonghoon/Login/Login.scss
  src/Pages/byeonghoon/Main/Main.js
  src/Pages/byeonghoon/Main/Main.scss
  src/Pages/byeonghoon/Main/MainCenter/MainCenter.js
  src/Pages/byeonghoon/Main/MainCenter/MainCenter.scss
  src/Pages/byeonghoon/Main/MainRight/MainRight.js
  src/Pages/byeonghoon/Main/MainRight/MainRight.scss
  src/Pages/byeonghoon/Main/Nav/Nav.js
  src/Pages/byeonghoon/Main/Nav/Nav.scss
  src/Routes.js
Labels: Status: Accepted

#7 [배정규] add: 로그인 버튼 활성화 및 메인 피드 댓글 기능 구현
  public/images/junggyoo/AppStoreImg.png
  public/images/junggyoo/GooglePlayImg.png
  public/images/junggyoo/loginMobileImg.png
  public/index.html
  src/Pages/junggyoo/Login/JunggyooLogin.js
  src/Pages/junggyoo/Login/junggyooLogin.scss
  src/Pages/junggyoo/Main/Feeds/Feed/CommentContainer.js
  src/Pages/junggyoo/Main/Feeds/Feed/CommentContainer.scss
  src/Pages/junggyoo/Main/Feeds/Feed/CommentList.js
  src/Pages/junggyoo/Main/Feeds/Feed/CommentList.scss
  src/Pages/junggyoo/Main/Feeds/Feed/Feed.js
  src/Pages/junggyoo/Main/Feeds/Feed/Feed.scss
  src/Pages/junggyoo/Main/Feeds/Feed/Form.js
  src/Pages/junggyoo/Main/Feeds/Feed/Form.scss
  src/Pages/junggyoo/Main/Feeds/Feeds.js
  src/Pages/junggyoo/Main/Feeds/Feeds.scss
  src/Pages/junggyoo/Main/JunggyooMain.js
  src/Pages/junggyoo/Main/Right/Right.scss
  src/Pages/junggyoo/Main/junggyooMain.scss
  src/Styles/reset.scss
  src/Styles/test.js
Labels: Status: 리뷰 요청

#8 [최운정] Add : 메인 댓글기능 완성
  src/Pages/weunjeong/Login/Login.js
  src/Pages/weunjeong/Main/Components/Feeds/AddComment.js
  src/Pages/weunjeong/Main/Components/Feeds/Feeds.js
  src/Pages/weunjeong/Main/Components/Feeds/Feeds.scss
  src/Pages/weunjeong/Main/Components/Feeds/FirstFeed.js
  src/Pages/weunjeong/Main/Components/Feeds/HiddenComment.js
  src/Pages/weunjeong/Main/Components/Feeds/SecondFeed.js
  src/Pages/weunjeong/Main/Components/Feeds/ShownComment.js
  src/Pages/weunjeong/Main/Components/Feeds/ThirdFeed.js
  src/Pages/weunjeong/Main/Components/Nav/ Nav.js
  src/Pages/weunjeong/Main/Main.js
  src/Pages/weunjeong/Main/Main.scss
Labels: Status: 리뷰 요청
